version: '3'

vars:
  output_dir: bin
  ludpkg: ./cmd/ludwig
  hlppkg: ./cmd/ludwighlpbld

tasks:
  setup:
    silent: true
    cmds:
      - mkdir -p {{.output_dir}}

  build:
    desc: Build debug binary
    deps: [setup]
    cmds:
      - go build -o {{.output_dir}}/ludwig-debug -gcflags "all=-N -l" {{.ludpkg}}

  build-release:
    desc: Build release binary
    deps: [setup]
    cmds:
      - go build -o {{.output_dir}}/ludwig -ldflags "-s -w" {{.ludpkg}}

  build-help:
    desc: Build help documentation
    deps: [build-hlpbld]
    cmds:
      - go run {{.hlppkg}} ludwighlp.txt {{.output_dir}}/ludwighlp.idx
      - go run {{.hlppkg}} ludwignewhlp.txt {{.output_dir}}/ludwignewhlp.idx

  build-hlpbld:
    desc: Build help documentation builder
    deps: [setup]
    cmds:
      - go build -o {{.output_dir}}/ludwighlpbld -ldflags "-s -w" {{.hlppkg}}

  test:
    desc: Run tests
    cmds:
      - go test ./internal/ludwig

  coverage:
    desc: Run tests with coverage
    cmds:
      - go test -coverprofile=coverage.out ./internal/ludwig
      - go tool cover -html=coverage.out

  system-test:
    desc: Run system tests if present
    if: '[ -x ./system-test/run-system-test.sh ]'
    cmds:
      - ./system-test/run-system-test.sh --showlocals

  check:
    desc: Run all checks
    cmds:
      - task: build
      - task: build-release
      - task: build-help
      - task: test
      - task: system-test

  clean:
    desc: Remove built binaries
    cmds:
      - rm -rf {{.output_dir}}
